### ISSUE TITLE
pdf modulünde hata 

### ISSUE THREAD

**Issue by chnyksl** [vpinar/E-Fatura-Goruntuleyici#2]
kendi projemde pdf modülünde openhtmltopdf kullandım tavsiye ederim zira Html2Pdf bende hata veriyor..
https://github.com/danfickle/openhtmltopdf

Elinize sağlık..

**Comment by vpinar** [comment]
Merhaba,
İlginiz için teşekkürler.
Kodları buraya koymamın amacı bu konuda çalışmak isteyen bir kişiye başlangıç noktası olmasıydı. İhtiyaç olması durumunda gönderdiğiniz alternatifi de deneyebilirim.
